/* Generated by: JavaCC 21 Parser Generator. Do not edit.
* Generated Code for EEIdentifier AST Node type
* by the ASTNode.java.ftl template
*/
package pt.up.fe.comp;

import static pt.up.fe.comp.JmmGrammarConstants.TokenType.*;


@SuppressWarnings("unused")
public class EEIdentifier extends BaseNode {
}


