/* Generated by: JavaCC 21 Parser Generator. Do not edit.
* Generated Code for FALSE Token subclass
* by the ASTToken.java.ftl template
*/
package pt.up.fe.comp;

import static pt.up.fe.comp.JmmGrammarConstants.TokenType.*;


@SuppressWarnings("unused")
public class FALSE extends Token {

    public FALSE(TokenType type, JmmGrammarLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


